twali-xyz/twali-xyz

components/HeaderNav/HeaderNav.tsx
components/SignUpSteps/SignUpSteps.tsx
package-lock.json
package.json
pages/index.tsx
pages/profile.tsx

- form validations
- some identity checks on profile page

Adding some form validation

---

components/HeaderNav/HeaderNav.tsx
components/Profile/EditExperienceModal/EditExperienceModal.tsx
components/Profile/EditProfileModal/EditProfileModal.tsx
components/Profile/Profile.tsx
components/Profile/SnapshotModal/SnapshotModal.tsx
components/SignUpSteps/SignUpSteps.tsx
package-lock.json
package.json
utils/walletUtils.tsx

Link to shortcut: https://app.shortcut.com/twali/story/54/integrate-snapshot-record-using-their-api
What it looks like:
What this PR includes:
- queries to get snapshot records, which are displayed on the UI with DAO ID, DAO Image, and vote count/total votes
- a utility file to move all the repeated wallet connect methods: `walletUtils.tsx`
- other cleanup of unused variables/methods

Integrate Snapshot record using their API

---

components/Profile/EditExperienceModal/EditExperienceModal.tsx
components/Profile/EditProfileModal/EditProfileModal.tsx
components/Profile/Profile.tsx
components/Profile/SnapshotModal/SnapshotModal.tsx
components/SignUpSteps/SignUpSteps.tsx
pages/_app.tsx

Link to shortcut: https://app.shortcut.com/twali/story/77/build-profile-field-validation
What this PR includes:
- Error validation for profile fields (except the dropdowns - there is a long delay on detecting the error which makes it confusing for the user so I omitted it for now)
- Design fixes including switching to dark mode
What it looks like:

Build profile field validation

---

README.md
components/Profile/Profile.tsx

Added a very basic readme and changed one word!

README & word change

---

components/SignUpSteps/SignUpSteps.tsx
pages/login.tsx

- added a login page
- to access this just do `<SITE URL>/login`
- login page was removed upon adding the new landing page, so just putting it back in so we can use it
- N/A
NA
NA

Added a login page

---

components/Landing/LottieAnimation.tsx
next-env.d.ts
pages/index.tsx
styles/global.css

Added styles to make landing page responsive 
- Uses default breakpoints provided by chakra-ui
none
https://user-images.githubusercontent.com/24376928/157013001-a4d2317d-c31a-4cad-9f14-561de02e9042.mov
none
https://app.shortcut.com/twali/story/468/make-lp-mobile-responsive

responsive landing page

---

components/HeaderNav/HeaderNav.tsx
components/Profile/CompanyModal/CompanyModal.tsx
components/Profile/EditExperienceModal/EditExperienceModal.tsx
components/Profile/EditProfileModal/EditProfileModal.tsx
components/Profile/ProfileDetails.tsx
components/SignUpSteps/SignUpSteps.tsx
data/dynamodb.js
infrastructure/provisionTable.js
pages/api/users/createUser.tsx
utils/profileUtils.tsx

- Ceramic and 3ID were completely removed from the UI
- Fully replaced the GET and POST User in the UI
- we still need a UPDATE/PUT user for the modals to be updated
- Completing migration from ceramic to dynamoDB
NA
NA
NA
https://app.shortcut.com/twali/story/335/migrate-profiles-from-ceramic-to-use-dynamodb

Migrate Profiles from ceramic to use dynamoDB

---

components/HeaderNav/HeaderNav.tsx
next-env.d.ts

- Created a new account on Alchemy with `eng@twali.xyz` and with this we'll be pointing to a new Alchemy Key
- I've also updated Vercel for now to include this new environment variable: `ALCHEMY_KEY_HTTP`
- Pls message me for the Alchemy Key!
- Moved Alchemy Key from my personal account to Twali's eng account
NA
NA
NA
https://app.shortcut.com/twali/story/513/change-alchemy-api-to-use-eng-account

added new alchemy key

---

components/HeaderNav/HeaderNav.tsx
components/Profile/CompanyModal/CompanyModal.tsx
components/Profile/EditExperienceModal/EditExperienceModal.tsx
components/Profile/EditProfileModal/EditProfileModal.tsx
components/Profile/Profile.tsx
components/Profile/SnapshotModal/SnapshotModal.tsx
components/SignUpSteps/SignUpSteps.tsx
utils/interfaces.ts

- created a file called `interfaces.ts` in the `utils` folder
- deleted interfaces from individual components
- imported interfaces where needed
- 
- cleans up the components/code maintenance 
none
none
none

moves interfaces to a seperate file and import where needed

---

components/Profile/Components/MultiSelect.tsx
components/Profile/EditProfileModal/EditProfileModal.tsx
components/Profile/ProfileSocialMedia.tsx
utils/profileUtils.tsx

- Added a cache and check for permissions in `profileUtils.ts`
- Reduces number of calls when opening modals and when loading the profile page
NA
https://user-images.githubusercontent.com/24376928/160107571-9af060e2-6998-45d4-8ebd-a93aa351848d.mov
NA
https://app.shortcut.com/twali/story/594/company-modal-opens-very-slowly

Reduce calls for modals

---

components/Profile/ProfileDetails.tsx

Fix for POAP Cors error
For production
NA
NA
NA
NA

Fix for POAP Cors error

---

components/Profile/CompanyModal/CompanyModal.tsx
components/Profile/EditProfileModal/EditProfileModal.tsx
components/Profile/ProfileDetails.tsx
pages/api/cors.tsx

- Changes to how state is managed in the companyModal
- Will ensure users can't save incorrect information in companyModals
- removed individual states for each input
- added tempCompany state to track changes
NA
https://app.shortcut.com/twali/story/571/company-modal-state-management-bug

Fix company modal state

---

components/Profile/CompanyModal/CompanyModal.tsx
components/Profile/Components/Chip.tsx
components/Profile/ProfileSideBar.tsx
pages/[userName].tsx
pages/login.tsx
pages/steps.tsx

- created a reusable <Chip/> component
- added titles to each page
- twali.xyz titles added to the tab for each page
na
na
na

add titles and create chip component

---

components/Profile/CompanyModal/CompanyModal.tsx
components/Profile/EditExpertiseModal/EditExpertiseModal.tsx
components/Profile/EditProfileModal/EditProfileModal.tsx
components/Profile/ProfileDetails.tsx
components/Profile/ProfileSideBar.tsx
components/Profile/ProfileWorkExperience.tsx
components/Profile/helpers/setEventArray.tsx
components/SignUpSteps/SignUpSteps.tsx
components/SignUpSteps/accountSelection.tsx
components/SignUpSteps/merchantProfileStep.tsx
components/SignUpSteps/professionalProfileStep.tsx
components/SignUpSteps/userProfileStep.tsx
components/TwaliContext.tsx
components/twaliReducer.tsx
pages/_app.tsx
pages/api/users/createUser.tsx
utils/interfaces.ts

- Added useContext hook to provide userData consistently throughout UI
- Added useReducer to simplify how we update the userData object
- Will provide consistent userData throughout the application
- No new states but current states are now managed/accessible through the useUser hook
- the highlighted code below was commented out leading to a "api did not send a response" error....not sure if this is what was leading to people having trouble signing up but we should look into this 
NA
https://app.shortcut.com/twali/story/621/building-state-management-to-handle-re-used-states-across-components

useContext & useReducer state management

---

components/reusable/TwaliSlider.tsx

- Fix UI bug where slider would show up over the calendar when open
NA
NA
Before
After
NA
NA

fix company modal UI bug

---

components/Profile/ProfileDetails.tsx
components/UserPermissionsProvider/enablePermission.ts
utils/walletUtils.tsx

- fixes the modal bug
- fixes public profile not being visible
NA
NA
NA
https://app.shortcut.com/twali/story/876/modals-freeze-on-main-profiles-and-metamask-check-breaks-public-view

high priority: fix for modal & wallet connect bug

---

components/Marketplace/BountyCard.tsx
components/Marketplace/BountyList.tsx
components/Marketplace/SelectWerkModal/SelectWerkModal.tsx
components/Profile/ProfileImageUpload.tsx
components/Project/Project.tsx
components/Project/ProjectDescription.tsx
components/Project/ProjectDescriptionModal/ProjectDescriptionModal.tsx
components/Project/ProjectDetails.tsx
components/Project/ProjectDetailsModal/ProjectDetailsModal.tsx
components/Project/ProjectExpertise.tsx
components/Project/ProjectExpertiseModal/ProjectExpertiseModal.tsx
components/Project/ProjectHeader.tsx
components/Project/ProjectHeaderModal/ProjectHeaderModal.tsx
components/SOWBuilderSteps/SOWBuilderSteps.tsx
components/SOWBuilderSteps/WerkTokenDropdown.tsx
components/SOWBuilderSteps/datesAndPricing.tsx
components/SOWBuilderSteps/statementOfWerk.tsx
components/SOWBuilderSteps/submissionOfWerk.tsx
context/BountyContext.tsx
context/TokenContext.tsx
context/bountyReducer.tsx
data/dynamodb.js
infrastructure/scripts/batch_write_table.py
pages/_app.tsx
pages/api/marketplace/submitBounty.tsx
pages/create-werk.tsx
utils/interfaces.ts
utils/marketplaceUtils.tsx

- Bounty context to handle all the bounty data across nested parent and children components
- Being able to edit and save data on Project modals
- Backend function to handle submitting a bounty
- Part of the SOW Builder
Quite a lot... But essentially look at the Bounty context for the major ones
NA
NA

Moving all the SOW Builder files into the feature branch - 719

---

infrastructure/provisionTable.js
serverless.yml

- this is the new version of our dynamoDB tables and will allow our deployments on staging to work correctly
NA
NA
NA
NA
NA

Change staging table to use Twali-core-test

---

components/HeaderNav/HeaderNav.tsx
components/Marketplace/BountyCard.tsx
components/Marketplace/BountyList.tsx
components/Marketplace/FilterInputs.tsx
components/Profile/CompanyModal/CompanyModal.tsx
components/Profile/ProfileDetails.tsx
components/reusable/Dropdown.tsx
components/reusable/Referral.tsx
components/reusable/TwaliSlider.tsx
data/dynamodb.js
pages/marketplace/[[...marketplace]].tsx
utils/interfaces.ts

- Added avatar/hamburger menu
- Link to copy referral link
- Link to copy job referral link in marketplace
- Fix company modal issues( -gradient match final badge, -fill color of currentStatus, -only show one extra badge in edit view, added delete/cancel button)
na
- na
na
https://app.shortcut.com/twali/story/941/fix-fill-for-currentstatus-in-company-modal
https://app.shortcut.com/twali/story/943/only-show-1-extra-badge-in-the-work-experience-section
https://app.shortcut.com/twali/story/947/make-gradients-match-in-modal-and-final-badge-for-fallback-logo
https://app.shortcut.com/twali/story/948/redo-how-we-shorten-addresses-in-the-navbar
https://app.shortcut.com/twali/story/949/create-avatar-hamburger-menu-dropdown

Feature-referrals - add referral links & company modal fixes

---

components/Whitelist/WhitelistForm.tsx
context/WhitelistReducer.tsx
pages/admin/whitelist.tsx
pages/loading.tsx
pages/whitelist/application.tsx

- Changed first question in whitelist from full name to 2 questions, first name & last name
- save referredBy data to user whitelist object when referral link is used
- still need to save job referral data after application flow is completed
- still need to save successful referral to the referrer's profile if referred member is approved after whitelist application
- in the whitelist/application the individual states representing the user(name, email, discord, etc) have been combined into one object(userWhitelistObj)
na
https://app.shortcut.com/twali/story/964/save-referral-to-database

Save referral

---

components/Admin/ApplicantList.tsx
data/dynamodb.js
hooks/useWhitelist.tsx
pages/_app.tsx
pages/admin/whitelist.tsx
pages/api/admin/retrieveWhitelist/[...userWallet].tsx
pages/api/admin/updateReferral.tsx
pages/api/admin/updateUser.tsx
pages/api/users/whitelist/[userWallet].tsx

- Add referral to referredUsers attribute of the referrer upon approval from the whitelist
- pushes the address of the referred user to the referredUsers attribute of the referrer
na
na
https://app.shortcut.com/twali/story/1008/save-referred-data-to-the-referrer-s-profile

Add referral to referredUsers attribute of the referrer

---

components/Profile/CompanyModal/CompanyModal.tsx
components/Profile/EditExpertiseModal/EditExpertiseModal.tsx
components/Profile/EditProfileModal/EditProfileModal.tsx
components/Profile/ProfileData/ProfileDataLayout.tsx
components/Profile/ProfileData/ProfileExpertise.tsx
components/Profile/ProfileData/ProfileInfo.tsx
components/Profile/ProfileDetails.tsx
components/Project/ProjectDetails.tsx
components/Project/ProjectDetailsModal/ProjectDetailsModal.tsx
pages/login.tsx
pages/marketplace/[[...marketplace]].tsx

- Fixes needing to reload after changing company info
- userState doesn't change to new user on going to profile
-  the userState is replaced with an empty state for some reason, that will need to be fixed but it is much better than showing another users info. They will simply need to log back in
- replaced the use of the useUser hook with useFetchUser to avoid setting userState to whoever's profile page is loaded
na
na
https://app.shortcut.com/twali/story/951/user-state-being-changed-when-visiting-other-user-profile

Profile user state

---

components/Profile/CompanyModal/CompanyModal.tsx
components/Profile/EditProfileModal/EditProfileModal.tsx
components/Profile/ProfileData/ProfileSocialMedia.tsx

- The social links no longer will show undefined URL
- Public view of company modal displays info correctly
- Prevent saving profile edit with invalid URL for social links
- small bugs
na
na

fix social links, public company modal, saving profile edit

---

components/Profile/CompanyModal/CompanyModal.tsx

- show saved expertises in company modal
- saved expertises were not being displayed
na
https://app.shortcut.com/twali/

show correct expertise when opening modal

---

components/Whitelist/WhitelistForm.tsx
pages/whitelist/application.tsx

- Added twitter input field and error handling for whitelist application
- Allows user to apply with twitter OR linkedIn URL
- added twitter to userWhitelistObj
na
https://app.shortcut.com/twali/

added twitter to whitelist application form
